FROM mcr.microsoft.com/dotnet/sdk:5.0

ADD . .

# RUN cd src/ && dotnet msbuild ./dir.proj -t:GenerateConstant && cd Runner.Client && dotnet build --disable-parallel

# RUN ./bin/Runner.Client --workflow workflow.yml --event push --payload payload.json --server http://localhost:5000

CMD ["/bin/bash"]